[package]
name = "bobtimus"
version = "0.1.0"
authors = [ "CoBloX Team <team@coblox.tech>" ]
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
elements-fun = { path = "../elements-fun" }
elements-harness = { path = "../elements-harness" }
futures = { version = "0.3", default-features = false }
hex = "0.4"
hmac = "0.10"
reqwest = "0.10"
rust_decimal = "1.8"
serde = { version = "1", features = [ "derive" ] }
sha2 = "0.9"
structopt = "0.3"
swap = { path = "../swap" }
tokio = { version = "0.2", features = [ "macros" ] }
warp = "0.2.5"

[dev-dependencies]
testcontainers = "0.11"