[package]
name = "elements-harness"
version = "0.1.0"
authors = ["CoBloX Team <team@coblox.tech>"]
edition = "2018"

[dependencies]
base64 = "0.12.3"
elements = { version = "0.13", features = ["serde-feature"] }
futures = "0.3.5"
log = "0.4"
hmac = "0.10"
hex = "0.4.2"
rand = "0.7"
reqwest = { version = "0.10", default-features = false, features = ["json", "native-tls"] }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.9"
testcontainers = "0.11"
thiserror = "1.0"
tokio = { version = "0.2", default-features = false, features = ["blocking", "macros", "rt-core", "time"] }
tracing = "0.1"
url = "2"

[features]
default = []
test-docker = []
