language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.29.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y binutils-dev libunwind8-dev

script:
  # Pin `cc` for Rust 1.29
  - if [ "$TRAVIS_RUST_VERSION" = "1.29.0" ]; then cargo generate-lockfile --verbose && cargo update -p cc --precise "1.0.41" --verbose; fi
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --features=serde-feature
  - cargo test --verbose --features=serde-feature
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cd fuzz && cargo test --verbose && ./travis-fuzz.sh; fi
