version: '3'
services:
  # RPC daemons
  liquid:
    image: vulpemventures/liquid:latest
    container_name: liquid-e2e-test
    networks:
      local:
        ipv4_address: 10.10.0.11
    ports:
      - 7041:18884
    volumes:
      - ./volumes/liquidregtest:/config
    restart: unless-stopped
  # Block explorer REST servers
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - 10.10.0.11:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    networks:
      local:
        ipv4_address: 10.10.0.13
    depends_on:
      - liquid
    ports:
      - 60401:60401
      - 3012:3002
    volumes:
      - ./volumes/liquidregtest:/config
    restart: unless-stopped
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    networks:
      local:
        ipv4_address: 10.10.0.15
    depends_on:
      - electrs-liquid
    environment:
      API_URL: http://localhost:5001
    ports:
      - 5001:5000
    restart: unless-stopped

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
