[package]
name = "swap"
version = "0.1.0"
authors = ["CoBloX Team <team@coblox.tech>"]
edition = "2018"

[dependencies]
bitcoin = { version = "0.25", features = ["rand"] }
secp256k1 = { version = "0.19.0", features = ["global-context"] }
elements = "0.13"
elements-harness = { path = "../elements-harness" }
sha2 = "0.9"
wally = { git = "https://github.com/RCasatta/wally", branch = "master" }

[dev-dependencies]
rand = "0.6"
testcontainers = "0.11"
tokio = { version = "0.2", default-features = false, features = ["blocking", "macros", "rt-core", "time"] }
